import type { GetLocations } from ".";

/**
 * Maps UI location slugs to exact venue.city values stored in the DB.
 * The search endpoint uses a case-sensitive keyword term filter — values
 * must match exactly what was saved when the venue was created.
 */
export const VENUE_CITY_MAP: Record<string, string> = {
  "ho-chi-minh": "Ho Chi Minh",
  "ha-noi": "Hanoi",
  "da-nang": "Da Nang",
  "hai-phong": "Hai Phong",
  "can-tho": "Can Tho",
  "an-giang": "An Giang",
  "ba-ria-vung-tau": "Ba Ria - Vung Tau",
  "bac-giang": "Bac Giang",
  "bac-kan": "Bac Kan",
  "bac-lieu": "Bac Lieu",
  "bac-ninh": "Bac Ninh",
  "ben-tre": "Ben Tre",
  "binh-dinh": "Binh Dinh",
  "binh-duong": "Binh Duong",
  "binh-phuoc": "Binh Phuoc",
  "binh-thuan": "Binh Thuan",
  "ca-mau": "Ca Mau",
  "cao-bang": "Cao Bang",
  "dak-lak": "Dak Lak",
  "dak-nong": "Dak Nong",
  "dien-bien": "Dien Bien",
  "dong-nai": "Dong Nai",
  "dong-thap": "Dong Thap",
  "gia-lai": "Gia Lai",
  "ha-giang": "Ha Giang",
  "ha-nam": "Ha Nam",
  "ha-tinh": "Ha Tinh",
  "hai-duong": "Hai Duong",
  "hau-giang": "Hau Giang",
  "hoa-binh": "Hoa Binh",
  "hung-yen": "Hung Yen",
  "khanh-hoa": "Khanh Hoa",
  "kien-giang": "Kien Giang",
  "kon-tum": "Kon Tum",
  "lai-chau": "Lai Chau",
  "lam-dong": "Lam Dong",
  "lang-son": "Lang Son",
  "lao-cai": "Lao Cai",
  "long-an": "Long An",
  "nam-dinh": "Nam Dinh",
  "nghe-an": "Nghe An",
  "ninh-binh": "Ninh Binh",
  "ninh-thuan": "Ninh Thuan",
  "phu-tho": "Phu Tho",
  "phu-yen": "Phu Yen",
  "quang-binh": "Quang Binh",
  "quang-nam": "Quang Nam",
  "quang-ngai": "Quang Ngai",
  "quang-ninh": "Quang Ninh",
  "quang-tri": "Quang Tri",
  "soc-trang": "Soc Trang",
  "son-la": "Son La",
  "tay-ninh": "Tay Ninh",
  "thai-binh": "Thai Binh",
  "thai-nguyen": "Thai Nguyen",
  "thanh-hoa": "Thanh Hoa",
  "thua-thien-hue": "Hue",
  "tien-giang": "Tien Giang",
  "tra-vinh": "Tra Vinh",
  "tuyen-quang": "Tuyen Quang",
  "vinh-long": "Vinh Long",
  "vinh-phuc": "Vinh Phuc",
  "yen-bai": "Yen Bai",
};

/** Convert a UI location slug to the exact city name expected by the search API. */
export function slugToVenueCity(slug: string): string | undefined {
  return VENUE_CITY_MAP[slug];
}

export const getLocations: GetLocations = () => [
  {
    label: "Thành phố",
    locations: [
      { value: "ho-chi-minh", label: "Hồ Chí Minh" },
      { value: "ha-noi", label: "Hà Nội" },
      { value: "da-nang", label: "Đà Nẵng" },
      { value: "hai-phong", label: "Hải Phòng" },
      { value: "can-tho", label: "Cần Thơ" },
    ],
  },
  {
    label: "Tỉnh",
    locations: [
      { value: "an-giang", label: "An Giang" },
      { value: "ba-ria-vung-tau", label: "Bà Rịa – Vũng Tàu" },
      { value: "bac-giang", label: "Bắc Giang" },
      { value: "bac-kan", label: "Bắc Kạn" },
      { value: "bac-lieu", label: "Bạc Liêu" },
      { value: "bac-ninh", label: "Bắc Ninh" },
      { value: "ben-tre", label: "Bến Tre" },
      { value: "binh-dinh", label: "Bình Định" },
      { value: "binh-duong", label: "Bình Dương" },
      { value: "binh-phuoc", label: "Bình Phước" },
      { value: "binh-thuan", label: "Bình Thuận" },
      { value: "ca-mau", label: "Cà Mau" },
      { value: "cao-bang", label: "Cao Bằng" },
      { value: "dak-lak", label: "Đắk Lắk" },
      { value: "dak-nong", label: "Đắk Nông" },
      { value: "dien-bien", label: "Điện Biên" },
      { value: "dong-nai", label: "Đồng Nai" },
      { value: "dong-thap", label: "Đồng Tháp" },
      { value: "gia-lai", label: "Gia Lai" },
      { value: "ha-giang", label: "Hà Giang" },
      { value: "ha-nam", label: "Hà Nam" },
      { value: "ha-tinh", label: "Hà Tĩnh" },
      { value: "hai-duong", label: "Hải Dương" },
      { value: "hau-giang", label: "Hậu Giang" },
      { value: "hoa-binh", label: "Hòa Bình" },
      { value: "hung-yen", label: "Hưng Yên" },
      { value: "khanh-hoa", label: "Khánh Hòa" },
      { value: "kien-giang", label: "Kiên Giang" },
      { value: "kon-tum", label: "Kon Tum" },
      { value: "lai-chau", label: "Lai Châu" },
      { value: "lam-dong", label: "Lâm Đồng" },
      { value: "lang-son", label: "Lạng Sơn" },
      { value: "lao-cai", label: "Lào Cai" },
      { value: "long-an", label: "Long An" },
      { value: "nam-dinh", label: "Nam Định" },
      { value: "nghe-an", label: "Nghệ An" },
      { value: "ninh-binh", label: "Ninh Bình" },
      { value: "ninh-thuan", label: "Ninh Thuận" },
      { value: "phu-tho", label: "Phú Thọ" },
      { value: "phu-yen", label: "Phú Yên" },
      { value: "quang-binh", label: "Quảng Bình" },
      { value: "quang-nam", label: "Quảng Nam" },
      { value: "quang-ngai", label: "Quảng Ngãi" },
      { value: "quang-ninh", label: "Quảng Ninh" },
      { value: "quang-tri", label: "Quảng Trị" },
      { value: "soc-trang", label: "Sóc Trăng" },
      { value: "son-la", label: "Sơn La" },
      { value: "tay-ninh", label: "Tây Ninh" },
      { value: "thai-binh", label: "Thái Bình" },
      { value: "thai-nguyen", label: "Thái Nguyên" },
      { value: "thanh-hoa", label: "Thanh Hóa" },
      { value: "thua-thien-hue", label: "Thừa Thiên Huế" },
      { value: "tien-giang", label: "Tiền Giang" },
      { value: "tra-vinh", label: "Trà Vinh" },
      { value: "tuyen-quang", label: "Tuyên Quang" },
      { value: "vinh-long", label: "Vĩnh Long" },
      { value: "vinh-phuc", label: "Vĩnh Phúc" },
      { value: "yen-bai", label: "Yên Bái" },
    ],
  },
];
